spring.application.name=mindspark-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mindspark_db
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true